In [6]:
import pandas as pd
import numpy as np

In [12]:
latents_data = pd.read_json('data/latents_results.json')
metadata = pd.read_csv('data/shapenet_metadata.csv')

In [13]:
latents_data.head(10)

,names,raw_data,style_latents,local_latents,eps
0,1f5e1b0661b340fc81dcc09cafd93d2e,"[[1.024717450141906, -0.717034637928009, 1.579...","[0.023511715233325, 0.167522728443145, -1.7323...","[1.024355173110962, -0.7397550344467161, 1.591...","[0.023511715233325, 0.167522728443145, -1.7323..."
1,68b62b9b9d49f262b12ea83455b0f44,"[[0.7599654793739311, 0.043263264000415004, -1...","[-0.064623266458511, 1.80087399482727, 0.56509...","[0.7530714273452751, 0.075030945241451, -1.254...","[-0.064623266458511, 1.80087399482727, 0.56509..."
2,575266906372ef117cc922af3684d251,"[[-0.9319659471511841, -0.42853677272796603, 0...","[0.250359177589416, 0.19480556249618503, 0.199...","[-0.9200506806373591, -0.48194885253906206, 1....","[0.250359177589416, 0.19480556249618503, 0.199..."
3,f3760c5e8b97149163b803b494079757,"[[-0.8434703946113581, -0.5776208639144891, -1...","[0.7646746635437011, 0.7314377427101131, 0.291...","[-0.840126097202301, -0.563672304153442, -2.00...","[0.7646746635437011, 0.7314377427101131, 0.291..."
4,6c449b92891754c6b8b6b17d4ce17d67,"[[-0.481881886720657, -0.43148025870323103, 1....","[0.6250587105751031, -0.025738298892974004, -0...","[-0.468885511159896, -0.604922354221344, 1.305...","[0.6250587105751031, -0.025738298892974004, -0..."
5,bb7ca919b59a3a2e6b418c7d9fedcaa9,"[[0.035457987338304006, -0.7526748180389401, 1...","[0.599034488201141, 1.644528865814209, 0.54934...","[0.033990882337093, -0.8384878039360041, 1.939...","[0.599034488201141, 1.644528865814209, 0.54934..."
6,609f09c6ce74d6c44c06afea25f8c085,"[[-0.487265288829803, 0.130332946777343, -2.53...","[1.9118846654891961, 1.7396173477172852, 1.219...","[-0.490228474140167, 0.18996152281761103, -2.5...","[1.9118846654891961, 1.7396173477172852, 1.219..."
7,ef3ed9f139571826ce27281f3b76d1f5,"[[-0.23396576941013303, -0.172266885638237, 2....","[0.027016922831535003, 0.05900937318801801, -1...","[-0.24473574757575903, -0.15292583405971502, 2...","[0.027016922831535003, 0.05900937318801801, -1..."
8,382496958e58e9a0658e57fd275f6bed,"[[0.8128136396408081, -0.390083700418472, 2.31...","[2.319842576980591, 0.92091166973114, 0.269147...","[0.804372906684875, -0.42203512787818903, 2.31...","[2.319842576980591, 0.92091166973114, 0.269147..."
9,a750b467d629df3e2268f50ab9844c64,"[[-0.15008972585201202, 1.084112167358398, 1.6...","[0.76055496931076, 0.954250395298004, -0.10381...","[-0.15126205980777702, 1.138327479362487, 1.68...","[0.76055496931076, 0.954250395298004, -0.10381..."

In [14]:
metadata.head(10)

,fullId,wnsynset,wnlemmas,up,front,name,tags
0,3dw.bcf0b18a19bce6d91ad107790a9e2d51,"04285965,03594945,02958343",SUV,"0.0\,0.0\,1.0000001","0.0\,-1.0000001\,0.0",Hummer H1 SUT,NaN
1,3dw.5876e90c8f0b15e112ed57dd1bc82aa3,02958343,"car,auto,automobile,machine,motorcar","0.0\,0.0\,1.0","0.0\,-1.0\,0.0",Alfa Romeo 156,NaN
2,3dw.402d1624e1c28422383a5be3771c595c,"03100240,04097373,02958343","convertible,roadster,runabout,two-seater","0.0\,0.0\,1.0","0.0\,-1.0\,0.0",1957 Chevrolet Bel Air,NaN
3,3dw.8fadf13734ff86b5f9e6f9c7735c6b41,02958343,"car,auto,automobile,machine,motorcar","0.0\,0.0\,1.0","1.0\,0.0\,0.0",Porsche Carrera GT (Tuned),NaN
4,3dw.ff267b1a6d986426c6df82b90873315e,"03119396,04322801,02958343","coupe,stock car","0.0\,0.0\,1.0","-1.0\,0.0\,0.0",Porsche 911 Turbo (996),NaN
5,3dw.e1c6002b98b4cb2c32f56cbc65681ab5,"03119396,02958343",coupe,"0.0\,0.0\,1.0","-1.0\,0.0\,0.0",Fiat 500,NaN
6,3dw.5edaef36af2826762bf75f4335c3829b,"02958343,04285965","car,auto,automobile,machine,motorcar,SUV","0.0\,0.0\,1.0","0.0\,-1.0\,0.0",Nissan Murano,NaN
7,3dw.8606a6353a2c0f7a453660f3d68cae6e,"03100240,04097373,02958343","convertible,roadster,runabout,two-seater","0.0\,0.0\,1.0","0.0\,-1.0\,0.0",BMW Z8 (Modified),NaN
8,3dw.7a228c811e7e18ad18e1879dc4ad8784,"04166281,04322801,02958343","sedan,saloon,stock car","0.0\,0.0\,1.0","-1.0\,0.0\,0.0",Lexus GS300 / Toyota Aristo,NaN
9,3dw.5523a6798194043146810e868f84ab51,"04166281,04322801,02958343","sedan,saloon,stock car","0.0\,0.0\,1.0","-1.0\,0.0\,0.0",VAZ 2106 / Lada 1600,NaN

In [ ]:
metadata['fullId'] = metadata['fullId'].replace(r'3dw.', '', regex=True)
metadata.drop(['up', 'front', 'tags', 'wnsynset'], axis=1, inplace=True)
# metadata.to_csv('data/metadata_trunc.csv', index=False)
metadata.head(10)

In [23]:
metadata_trunc = pd.read_csv('data/metadata_trunc.csv')
metadata_trunc.head(10)
metadata_trunc.wnlemmas.value_counts()

car               902
coupe             507
sedan             440
racing car        345
SUV               326
convertible       241
sports car        200
police cruiser    179
wagon              88
ambulance          73
off-road           65
limousine          60
roadster           34
hot rod            19
minivan            14
hatchback          11
compact             6
muscle car          3
pickup              2
Name: wnlemmas, dtype: int64

In [24]:
metadata_combined = metadata_trunc.copy(True)
metadata_combined['wnlemmas'].replace({'pickup' : 'SUV', 
                                       'off-road' : 'SUV', 
                                       'roadster' : 'convertible',
                                       'racing car' : 'sports car',
                                       'muscle car' : 'sports car',
                                       'minivan' : 'SUV',
                                       'hatchback' : 'compact'}, inplace=True)
metadata_combined.wnlemmas.value_counts()

car               902
sports car        548
coupe             507
sedan             440
SUV               407
convertible       275
police cruiser    179
wagon              88
ambulance          73
limousine          60
hot rod            19
compact            17
Name: wnlemmas, dtype: int64

In [25]:
latents_data = latents_data.join(metadata_combined.set_index('fullId'), on='names')

In [27]:
print(len(latents_data))
latents_data.head(10)

3514

,names,raw_data,style_latents,local_latents,eps,wnlemmas,name
0,1f5e1b0661b340fc81dcc09cafd93d2e,"[[1.024717450141906, -0.717034637928009, 1.579...","[0.023511715233325, 0.167522728443145, -1.7323...","[1.024355173110962, -0.7397550344467161, 1.591...","[0.023511715233325, 0.167522728443145, -1.7323...",SUV,Landrover Defender
1,68b62b9b9d49f262b12ea83455b0f44,"[[0.7599654793739311, 0.043263264000415004, -1...","[-0.064623266458511, 1.80087399482727, 0.56509...","[0.7530714273452751, 0.075030945241451, -1.254...","[-0.064623266458511, 1.80087399482727, 0.56509...",car,Nouvelle Renault 4 L 2012
2,575266906372ef117cc922af3684d251,"[[-0.9319659471511841, -0.42853677272796603, 0...","[0.250359177589416, 0.19480556249618503, 0.199...","[-0.9200506806373591, -0.48194885253906206, 1....","[0.250359177589416, 0.19480556249618503, 0.199...",sports car,Tuned Toyota Supra
3,f3760c5e8b97149163b803b494079757,"[[-0.8434703946113581, -0.5776208639144891, -1...","[0.7646746635437011, 0.7314377427101131, 0.291...","[-0.840126097202301, -0.563672304153442, -2.00...","[0.7646746635437011, 0.7314377427101131, 0.291...",ambulance,GMC AMBULANCE
4,6c449b92891754c6b8b6b17d4ce17d67,"[[-0.481881886720657, -0.43148025870323103, 1....","[0.6250587105751031, -0.025738298892974004, -0...","[-0.468885511159896, -0.604922354221344, 1.305...","[0.6250587105751031, -0.025738298892974004, -0...",sedan,77 holden a9x torana
5,bb7ca919b59a3a2e6b418c7d9fedcaa9,"[[0.035457987338304006, -0.7526748180389401, 1...","[0.599034488201141, 1.644528865814209, 0.54934...","[0.033990882337093, -0.8384878039360041, 1.939...","[0.599034488201141, 1.644528865814209, 0.54934...",SUV,2005 Ford Excursion SLT
6,609f09c6ce74d6c44c06afea25f8c085,"[[-0.487265288829803, 0.130332946777343, -2.53...","[1.9118846654891961, 1.7396173477172852, 1.219...","[-0.490228474140167, 0.18996152281761103, -2.5...","[1.9118846654891961, 1.7396173477172852, 1.219...",sports car,Consept car (close to compleat needs detail work)
7,ef3ed9f139571826ce27281f3b76d1f5,"[[-0.23396576941013303, -0.172266885638237, 2....","[0.027016922831535003, 0.05900937318801801, -1...","[-0.24473574757575903, -0.15292583405971502, 2...","[0.027016922831535003, 0.05900937318801801, -1...",convertible,Chevrolet Camaro SS convertible
8,382496958e58e9a0658e57fd275f6bed,"[[0.8128136396408081, -0.390083700418472, 2.31...","[2.319842576980591, 0.92091166973114, 0.269147...","[0.804372906684875, -0.42203512787818903, 2.31...","[2.319842576980591, 0.92091166973114, 0.269147...",car,Shimmy E-TRONIC [Electric Concept Car]
9,a750b467d629df3e2268f50ab9844c64,"[[-0.15008972585201202, 1.084112167358398, 1.6...","[0.76055496931076, 0.954250395298004, -0.10381...","[-0.15126205980777702, 1.138327479362487, 1.68...","[0.76055496931076, 0.954250395298004, -0.10381...",car,Scion xA (Tuned)

In [28]:
latents_data.to_csv('LION_latents.csv', index=False)